### ISSUE TITLE
Enhancement: add "request" as a parameter in the method get_list_query

### ISSUE THREAD

**Issue by whchi** [jowilf/starlette-admin#384] opened 2023-11-06 10:00 UTC
**Is your feature request related to a problem? Please describe.**
I am developing a feature that requires filtering my relationships based on a specific column.

The relationship is such that 1 post can have N categories. When I am on my category page.

I want to select posts where the **status is "published" and deleted_at is "None"**.

**Describe the solution you'd like**
I found this discussion https://github.com/jowilf/starlette-admin/issues/236 which helped me in resolving my issue.

**Describe alternatives you've considered**
I have also considered whether there is a way for the current model to know where the request is coming from when using `get_list_query`.

**Additional context**
I have overridden the `get_list_query` as follows:
```py
    def get_list_query(self, referer: str | None) -> Select:
        if referer:
            import urllib.parse
            path = urllib.parse.urlparse(referer).path
            for field in self.fields:
                if isinstance(field, HasOne) and field.identity == 'categories' and path.startswith('/admin/categories'):
                    return select(self.model).where(
                        self.model.status == Status.PUBLISHED,
                        is_(self.model.deleted_at, None),
                    )
```
The async def find_all method seems a bit complicated:
```py
    async def find_all(
            self,
            request: Request,
            skip: int = 0,
            limit: int = 100,
            where: Union[Dict[str, Any], str, None] = None,
            order_by: Optional[List[str]] = None,
    ) -> Sequence[Any]:
        ...
        # The only line I need is to add the referer from request.headers
        stmt = self.get_list_query(request.headers.get('referer')).offset(skip)
        ... # rest of the original code
```
If it is possible to pass the request into the get_list_query method, then there might be no need to override the async def find_all method.

**Comment by sglebs** [comment] 2023-11-07 16:26
I also needed this. I added it manually, see #274

**Comment by hasansezertasan** [comment] 2023-11-10 11:11
I also need this one.

What do you think about this one @jowilf?

**Comment by jowilf** [comment] 2024-01-29 17:51
Duplicate of #489

**Closed** 2024-01-29 17:52 UTC
Labels: enhancement
